### PR TITLE
[LWD] test(e2e): fix entrypoint.swap flakiness with root-scoped swap POM

### PR DESCRIPTION
**Pull request by cunhabruno**
### 📝 Description

Re-lands the `entrypoint.swap` flakiness fix (previously #19704, reverted in #19873) with the semantic conflict resolved.

**Problem:** on the Asset Detail page (aggregatedAssets ON) the embedded swap rail was located with a **page-wide** `swap-web-app-container-embedded` selector. When an embedded swap from the previously visited screen was still mounted, the selector could match more than one element — or resolve to the wrong screen's swap — causing flaky, timing-dependent failures.

**Fix:** scope the swap rail (and the Asset Detail page's own locators) to the current page root, adopting the component-based page-object pattern from #16706.

- **PageView**: add a `page-view-<path>` root testid that mirrors the route verbatim, giving each page an exact, unambiguous anchor. The testid is derived in the view model (`getPageTestId` in `utils.ts` → `pageTestId`), keeping the View presentational.
- **`AppPage.pageView()`** helper + new **`SwapContainer`** component scoped to a parent locator (following the `AssetsTable` precedent).
- **`AssetDetailPage`**: takes the asset id, resolves its page root, and scopes its in-page locators to it. Portaled Lumen `Dialog`/`Menu` content (PnL dialog, favorite menu items) intentionally stay page-wide.
- **`index.ts`**: `assetDetail` is now an `assetId` factory; updated callers in `assets.aggregation` and `delegate` specs.

### 🔁 Why the previous PR was reverted

`develop` had trimmed the `PageView` view model's public surface so `pathname` was no longer exposed, but the reverted change still referenced it in `PageView` → `TS2304: Cannot find name 'pathname'`. This version threads a ready `pageTestId` through the view model instead, so the View no longer depends on a raw `pathname` prop.

### ❓ Context

- **JIRA**: [QAA-1406](https://ledgerhq.atlassian.net/browse/QAA-1406)
- Failing job (original): https://github.com/LedgerHQ/ledger-live/actions/runs/29472883044/job/87539485233
- Pattern precedent: #16706
- Previous PR / revert: #19704 / #19873

### ✅ Checklist

- [ ] `npx changeset` — n/a (test-only + internal testid, no package published)
- [x] Covered by automatic tests (this *is* an e2e test fix)
- [x] Ran locally against Speculos: `Entry Point - Asset Allocation` and `Market page - More than one account` both pass.
- [ ] **QA focus:** Swap entry-point suite (Asset Allocation and Market → asset entry points) with `aggregatedAssets` enabled.

[QAA-1406]: https://ledgerhq.atlassian.net/browse/QAA-1406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by cunhabruno** [comment]
## 🧪 Triggered test workflow

Manually dispatched on `test/qaa-1406-fix-entrypoint-swap-flaky` (commit a76791432b1), full desktop suite:

| Workflow | Scope | Run |
|---|---|---|
| [Desktop] E2E Only | full suite, Speculos nanoSP | [run 29864939857](https://github.com/LedgerHQ/ledger-live/actions/runs/29864939857) |

File: e2e/desktop/tests/page/assetDetail.page.ts [hunk 1]
```diff
@@ -1,35 +1,59 @@
...
-  // The staking section renders either the "earn banner" (not yet staked) or the "earn deposit"
-  // card (already staked); both open the same stake flow.
-  private readonly earnEntry = this.page
-    .getByTestId("asset-detail-earn-banner")
-    .or(this.page.getByTestId("asset-detail-earn-deposit"));
+
+  constructor(page: Page, assetId: string) {
+    super(page);
+    this.assetId = assetId;
+    this.assetDetailRoot = this.pageView(`asset/${this.assetId}`);
```
Comment (martijnhjk) [inline e2e/desktop/tests/page/assetDetail.page.ts:36]: Have you considered using getters for these instead? It will reduce the constructor and delay the execution until the property is called, eg:
```
get assetDetailRoot() {
  return this.pageView(`asset/${this.assetId}`);
}

get header(): Locator {
  return this.assetDetailRoot.getByTestId("asset-detail-header");
}
...
```

Comment (cunhabruno) [reply e2e/desktop/tests/page/assetDetail.page.ts:36]: Thanks for the suggestion! 🙏 I don't think getters buy us much here though. Playwright locators are already lazy: creating one just builds a selector string, and the DOM isn't queried until an action/assertion actually runs on it. So field/constructor assignment vs. a getter makes no difference to when the DOM is hit.

I'd rather keep constructor/field assignment here to stay consistent with the current POM pattern ([#16706](https://github.com/LedgerHQ/ledger-live/issues/16706)). If we do want to move to getters for some reason, let's do it as a separate, repo-wide change rather than diverging in this one file. 👍

Comment (martijnhjk) [reply e2e/desktop/tests/page/assetDetail.page.ts:36]: OK I was also suggesting in terms of readability. Smaller constructor and no need to declare the property explicitly and assign a value elsewhere. PRs would be less noisy too with getters because the property and the value are declared in one place so more contextual and less diff.

**Review by martijnhjk — APPROVED** [review]

**Review by LucasWerey — APPROVED** [review]
